cd '/Users/julianashwin/Documents/GitHub/EcoNNet.jl/estimation/general';

addpath /Applications/Dynare/4.6.4/matlab
clear;
close all;

%% Set parameters and solve the determinate model

phi_yy = 0.9; % persistence of y_t
phi_yp = 0.1; % feedback from p to y
phi_pp = 0.95; % discount factor on future dividends
phi_py = 0.5; % feedback from output to dividends
phi_py = (phi_py - 12*0.1125);
sigma_s = 0.5; % ``supply" shock variance
sigma_d = 0.5; % ``demand" shock variance
alpha_py = 0; % nonlinearity in p-y relationship
rho_d = 0; % persistence of demand shock
rho_s = 0; % persistence of supply shock

save param_general_det phi_yy phi_yp phi_pp phi_py sigma_s sigma_d alpha_py rho_d rho_s

% Solve and simulate the linear determinate model
dynare general_det noclearall nolog

% Estimate determinate model on data generated by dynare
dynare general_det_est noclearall nolog

% Estimate on learning data
dynare general_det_est_learn noclearall nolog



%%  Set parameters and solve the indeterminate model with a sunspot shock

close all

phi_yy = 0.9; % persistence of y_t
phi_yp = 0.1; % feedback from p to y
phi_pp = 0.95; % discount factor on future dividends
phi_py = 0.5; % feedback from output to dividends
sigma_s = 0.5; % ``supply" shock variance
sigma_d = 0.5; % ``demand" shock variance
sigma_z = 0.5; % ``sunspot" shock variance
alpha_py = 0; % nonlinearity in p-y relationship
rho_d = 0; % persistence of demand shock
rho_s = 0; % persistence of supply shock
omega12 = 0; % covariance of epsilon_s and epsilon_d
omega13 = 0.3; % covariance of epsilon_s and sunspot
omega23 = 0.1; % covariance of epsilon_d and sunspot

save param_general_indet phi_yy phi_yp phi_pp phi_py alpha_py rho_d rho_s ... 
    sigma_s sigma_d sigma_z omega12 omega13 omega23

% Solve and simulate the linear indeterminate model with sunspots
dynare general_indet noclearall nolog

% Estimate the linear sunspot model on data generated by dynare
dynare general_indet_est noclearall nolog

% Estimate the linear sunspot model on learning data
dynare general_indet_est_learn noclearall nolog



%%%%%%%%%%%%%%%%%%%%%%%% End %%%%%%%%%%%%%%%%%%%%%%%%